routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Request as req;
use App\Models\UserRole;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register' => false]);

$restrictScope = function($roles){
    try {
        $result = UserRole::whereIn('role',$roles)->get()->pluck("id")->toArray();
        return implode(',',$result);
    } catch (\Throwable $th) {
        return null;
    }
};

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::middleware('checkRole:'.$restrictScope(['superuser']))->prefix('/superuser')->name('superuser.')->group(function () {
  // Superuser
  Route::get('/', 'Superuser\SuperuserController@index')->name('superuser');

  //Superuser - Settings
  Route::prefix('/settings')->group(function () {

    Route::match(['get','post'],'general', 'Superuser\SettingsController@general')->name('Genel Ayarlar');
    Route::get('newsletter', 'Superuser\SettingsController@newsletter')->name('Bülten İstekleri');

    // Settings - Users
    Route::prefix('users')->group(function(){
        Route::get('/', 'Superuser\SettingsController@users')->name('Kullanıcı Yönetimi');
        Route::match(['post','get'],'/create', 'Superuser\SettingsController@users_create')->name('Yeni Kullanıcı Ekle');
        Route::match(['post','get'],'/edit/{id}', 'Superuser\SettingsController@users_edit')->name('Kullanıcı Düzenle');
    });
    // Superuser - Settings - silme işlemleri
    Route::match(['get','post'],'del', 'Superuser\SettingsController@delete')->name('settings_delete');

  });

  //Superuser - Forms
  Route::prefix('/forms')->group(function () {
    Route::get('/', 'Superuser\FormController@index')->name('Formlar');
    Route::match(['get','post'],'edit/{id}', 'Superuser\FormController@FormEdit')->name('Form Düzenle');
    Route::match(['get','post'],'create', 'Superuser\FormController@FormCreate')->name('Form Oluştur');
  });

  //Superuser - CMS Yönetimi
  Route::prefix('/cms')->group(function () {
    Route::get('/{id}', 'Superuser\CmsController@index')->name('CMS Yönetimi');
    Route::match(['post','get'],'/create/{parent_id}', 'Superuser\CmsController@create')->name('İçerik Oluştur');
    Route::match(['post','get'],'/edit/{id}', 'Superuser\CmsController@edit')->name('İçerik Düzenle');
    Route::match(['post','get'],'/delete/{id}', 'Superuser\CmsController@delete')->name('İçerik Sil');
    Route::match(['post','get'],'/delete/file/{id}', 'Superuser\CmsController@fileDelete')->name('Dosya Sil');
  });


  //Superuser - Language
  Route::prefix('/language')->group(function () {
    Route::get('/', 'Superuser\LanguageController@index')->name('language');
    // Language - create,edit,delete
    Route::match(['get','post'],'create', 'Superuser\LanguageController@create')->name('language_create');
    Route::match(['get','post'],'edit/{id}', 'Superuser\LanguageController@edit')->name('language_edit');
    Route::get('delete/{id}', 'Superuser\LanguageController@delete')->name('language_delete');
    Route::get('initialize/{lang}', 'Superuser\LanguageController@initializeLanguage')->name('language_init');
    Route::get('checklangs', 'Superuser\LanguageController@checkLangs')->name('check languages');
  });

  //Superuser - System
  Route::prefix('/system')->group(function () {
    Route::get('/', 'Superuser\SystemController@index')->name('system');
    //cache clear
    Route::get('/clear/cache', 'Superuser\SystemController@cacheClear')->name('system.clearcache');

    //maintenance mode
    Route::get('/up', 'Superuser\SystemController@systemUp')->name('system.up');
    Route::get('/down', 'Superuser\SystemController@systemDown')->name('system.down');

    //migrate
    Route::get('/migrate', 'Admin\SystemController@databaseMigrate')->name('system.migrate');
  });

});

Route::middleware('checkRole:'.$restrictScope(['superuser','admin']))->prefix('/admin')->group(function () {
    // Admin
    Route::get('/', 'Admin\AdminController@index')->name('admin');

    //Admin - Settings
    Route::prefix('/settings')->group(function () {

      Route::match(['get','post'],'general', 'Admin\SettingsController@general')->name('Genel Ayarlar');
      Route::get('newsletter', 'Admin\SettingsController@newsletter')->name('Bülten İstekleri');

      // Settings - Users
      Route::prefix('users')->group(function(){
          Route::get('/', 'Admin\SettingsController@users')->name('Kullanıcı Yönetimi');
          Route::match(['post','get'],'/create', 'Admin\SettingsController@users_create')->name('Yeni Kullanıcı Ekle');
          Route::match(['post','get'],'/edit/{id}', 'Admin\SettingsController@users_edit')->name('Kullanıcı Düzenle');
      });
      // Admin - Settings - silme işlemleri
      Route::match(['get','post'],'del', 'Admin\SettingsController@delete')->name('settings_delete');

    });

    //Admin - Forms
    Route::prefix('/forms')->group(function () {
      Route::get('/', 'Admin\FormController@index')->name('Formlar');
      Route::match(['get','post'],'edit/{id}', 'Admin\FormController@FormEdit')->name('Form Düzenle');
      Route::match(['get','post'],'create', 'Admin\FormController@FormCreate')->name('Form Oluştur');
    });

    //Admin - CMS Yönetimi
    Route::prefix('/cms')->group(function () {
      Route::get('/{id}', 'Admin\CmsController@index')->name('CMS Yönetimi');
      Route::match(['post','get'],'/create/{parent_id}', 'Admin\CmsController@create')->name('İçerik Oluştur');
      Route::match(['post','get'],'/edit/{id}', 'Admin\CmsController@edit')->name('İçerik Düzenle');
      Route::match(['post','get'],'/delete/{id}', 'Admin\CmsController@delete')->name('İçerik Sil');
      Route::match(['post','get'],'/delete/file/{id}', 'Admin\CmsController@fileDelete')->name('Dosya Sil');
    });


    //Admin - Language
    Route::prefix('/language')->group(function () {
      Route::get('/', 'Admin\LanguageController@index')->name('language');
      // Language - create,edit,delete
      Route::match(['get','post'],'create', 'Admin\LanguageController@create')->name('language_create');
      Route::match(['get','post'],'edit/{id}', 'Admin\LanguageController@edit')->name('language_edit');
      Route::get('delete/{id}', 'Admin\LanguageController@delete')->name('language_delete');
      Route::get('initialize/{lang}', 'Admin\LanguageController@initializeLanguage')->name('language_init');
      Route::get('checklangs', 'Admin\LanguageController@checkLangs')->name('check languages');
    });

    //Admin - System
    Route::prefix('/system')->group(function () {
      Route::get('/', 'Admin\SystemController@index')->name('system');
        //cache clear
        Route::get('/clear/cache', 'Admin\SystemController@cacheClear')->name('system.clearcache');

        //maintenance mode
        Route::get('/up', 'Admin\SystemController@systemUp')->name('system.up');
        Route::get('/down', 'Admin\SystemController@systemDown')->name('system.down');

        //migrate
        Route::get('/migrate', 'Admin\SystemController@databaseMigrate')->name('system.migrate');
    });

  });

// Change Language slug Session
Route::post('/lang/changelang', function (Request $request) {
    $langQuery = DB::table('language')->where('slug',$request->input('change_lang'))->first();
    session(['lang_slug' => $request->input('change_lang'), 'lang_name' => $langQuery->name]);
    return redirect()->back();
})->name('ChangeLang');

// User
Route::middleware('checkRole:'.$restrictScope(['user']))->prefix('/user')->group(function () {
  // User
  Route::get('/', 'User\UserController@index')->name('user');

  //User - CMS Yönetimi
  Route::prefix('/cms')->group(function () {
    Route::get('/{id}', 'User\CmsController@index')->name('user.CMS Yönetimi');
    Route::match(['post','get'],'/create/{parent_id}', 'User\CmsController@create')->name('user.İçerik Oluştur');
    Route::match(['post','get'],'/edit/{id}', 'User\CmsController@edit')->name('user.İçerik Düzenle');
    Route::match(['post','get'],'/delete/{id}', 'User\CmsController@delete')->name('user.İçerik Sil');
    Route::match(['post','get'],'/delete/file/{id}', 'User\CmsController@fileDelete')->name('user.Dosya Sil');
  });

  // Settings - Profile Edit
  Route::match(['post','get'],'profile/edit/', 'User\SettingsController@users_edit')->name('Profil Düzenle');

});

//ajax ve json işlemleri
Route::prefix('/misc')->group(function (){
    Route::get('/json/{name}.json', 'Web\AjaxController@textToJson');
    Route::get('/download/{dosya}', 'Web\BaseController@getDownload')->name('download');
});

Route::get('/', 'Web\BaseController@index');
Route::get('/{slug}', 'Web\BaseController@index');
Route::get('/{language_id}/{slug}', 'Web\BaseController@index');

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;
}

app/Http/Controllers/Admin/SettingsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use App\User;
use App\Models\UserRole;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class SettingsController extends Controller
{

    public function general(Request $request)
    {
      $slug = session('lang_slug');
      $lang_name = session('lang_name');
      $settings = DB::table('settings')->where('language_id',$slug)->first();

      if ($request->isMethod('post')) {

        // logo
        if ($request->hasFile('logo')) {
          Storage::delete($settings->logo);
          $logo = $request->logo->store('');
        }else {
          $logo = $settings->logo;
        }
        // footer logo
        if ($request->hasFile('footerlogo')) {
          Storage::delete($settings->footer_logo);
          $footerlogo = $request->footerlogo->store('');
        }else {
          $footerlogo = $settings->footer_logo;
        }

        // Varsayılan Dil
        $default_lang = $request->input('default_lang') ?: null;

        if ($default_lang) {
          //varsayilan baska dil varsa sıfırla
          $lang_exist = DB::table('settings')->where('default_lang',1)->exists(); // varsa 1 döndürecek
          if ($lang_exist) {
            DB::table('settings')->where('default_lang',1)->update([
              'default_lang' => 0
            ]);
          }
        }

        $special_field = json_encode($request->input('special'));

        // Settings Güncelle
        DB::table('settings')->where('language_id',$slug)->update([
          'logo' => $logo,
          'footer_logo' => $footerlogo,
          'default_lang' => $default_lang,
          'special_fields' => $special_field
        ]);

        return redirect()->back()->with('success','Başarıyla Güncellendi.');

      }

      return view('admin.Settings.index',[
        'settings' => $settings,
        'slug' => $slug,
        'lang_name' => $lang_name
      ]);
    }

    public function delete(Request $request)
    {
      $slug = session('lang_slug');
      $lang_name = session('lang_name');

      $case = $request->get('case');
      $settings = DB::table('settings')->where('language_id',$slug);

      switch ($case) {
        case 'logo':

            Storage::delete($settings->first()->logo);
            $settings->update([
              'logo' => null
            ]);
            return redirect()->back()->with('success','Logo Başarıyla Silindi.');

        break;

        case 'footer_logo':

            Storage::delete($settings->first()->footer_logo);
            $settings->update([
              'footer_logo' => null
            ]);
            return redirect()->back()->with('success','Footer Logo Başarıyla Silindi.');

        break;

        case 'userdel':

            $userid = $request->get('userid');
            $del = User::destroy($userid);
            if ($del) {
              return redirect()->back()->with('success','Kullanıcı Başarıyla Silindi.');
            }

        break;

        case 'newsletter':
            $id = $request->get('id');
            $del = DB::table('newsletter')->where('id',$id)->delete();
            if ($del) {
              return redirect()->back()->with('success','Başarıyla Silindi.');
            }

        break;

        default:
          return redirect()->back();
          break;
      }
    }

    public function users(Request $request)
    {
      $users = DB::table('users')->get();
      return view('admin.Settings.users.index',[
        'users' => $users
      ]);
    }



    public function users_create(Request $request)
    {
      if ($request->isMethod('post')) {

        $validatedData = $request->validate([
          'ad-soyad' => ['required', 'string', 'max:255'],
          'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
          'password' => ['required', 'string', 'min:8'],
          'role' => ['required', 'integer', Rule::in(UserRole::all()->pluck('id')->toArray())]
        ]);

        User::create([
            'name' => $request['ad-soyad'],
            'email' => $request['email'],
            'password' => Hash::make($request['password']),
            'role' => $request['role'],
        ]);
        return redirect()->back()->with('success','Kullanıcı Başarıyla Eklendi');

      }
      $roles = DB::table("user_roles")->get();
      return view('admin.Settings.users.create',[
          'roles' => $roles
      ]);
    }

    public function users_edit(Request $request,$id)
    {
      $user = User::find($id);
      if ($request->isMethod('post')) {

        $validatedData = $request->validate([
          'ad-soyad' => ['required', 'string', 'max:255'],
          'email' => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($id)],
          'role' => ['required', 'integer', Rule::in(UserRole::all()->pluck('id')->toArray())]
        ]);

        if ($request->input('password')) {
          $validatedData = $request->validate([
            'password' => ['required','string', 'min:8'],
          ]);
          $password = Hash::make($request['password']);
        }else {
          $password = $user->password;
        }

        User::updateOrCreate([
          'id' => $id
        ],[
            'name' => $request['ad-soyad'],
            'email' => $request['email'],
            'password' => $password,
            'role' => $request['role'],
        ]);
        return redirect()->back()->with('success','Kullanıcı Başarıyla Güncellendi');

      }
      $roles = DB::table("user_roles")->get();
      return view('admin.Settings.users.edit',[
        'user' => $user,
        'roles' => $roles
      ]);
    }

    public function newsletter()
    {
      $newsletters = DB::table('newsletter')->get();
      return view('admin.Settings.newsletter',[
        'newsletters' => $newsletters
      ]);
    }

}

app/Http/Controllers/User/SettingsController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use App\User;
use Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class SettingsController extends Controller
{
  public function users_edit(Request $request)
  {
    $id = Auth::user()->id;
    $user = User::find($id);
    if ($request->isMethod('post')) {

      $validatedData = $request->validate([
        'ad-soyad' => ['required', 'string', 'max:255'],
        'email' => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($id)],
      ]);

      if ($request->input('password')) {
        $validatedData = $request->validate([
          'password' => ['required','string', 'min:8'],
        ]);
        $password = Hash::make($request['password']);
      }else {
        $password = $user->password;
      }

      User::where("id",$id)->update([
          'name' => $request['ad-soyad'],
          'email' => $request['email'],
          'password' => $password
      ]);
      return redirect()->back()->with('success','Kullanıcı Başarıyla Güncellendi');

    }
    return view('user.Settings.users.edit',[
      'user' => $user
    ]);
  }
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index(Request $request)
    {
      return view("user.home");
    }
}

resources/views/superuser/Settings/users/create.blade.php
@extends('layouts.superuser-base')

@section('content')

<div class="row">
  <div class="col-12">
  <div class="card">
  <div class="card-header"><strong>Yeni Kullanıcı</strong> <small>Ekle</small> </div>
  <form action="" method="post" enctype="multipart/form-data">
    @csrf
  <div class="card-body">

  <div class="form-group row">
  <label class="col-md-2 col-form-label" for="text-input">Ad Soyad</label>
  <div class="col-md-10">
  <input class="form-control" id="text-input" type="text" name="ad-soyad" placeholder="Ad Soyad">
  </div>
  </div>
  <div class="form-group row">
  <label class="col-md-2 col-form-label" for="email-input">E-Mail</label>
  <div class="col-md-10">
  <input class="form-control" id="email-input" type="email" name="email" placeholder="ornek@gmail.com" autocomplete="email">
  </div>
  </div>
  <div class="form-group row">
  <label class="col-md-2 col-form-label" for="password-input">Şifre</label>
  <div class="col-md-10">
  <input class="form-control" aria-describedby="passHelp" id="password-input" type="password" name="password" placeholder="Şifre" autocomplete="new-password">
  <small id="passHelp" class="form-text text-muted">Herhangi Bir Şifre Girilmezse Eski Şifre Kullanılmaya Devam Edilecektir.</small>
  </div>
  </div>

  <div class="form-group row">
  <label class="col-md-2 col-form-label" for="select1">Rol</label>
  <div class="col-md-10">
  <select class="form-control" id="select1" name="role">
  <option value="null" selected disabled hidden> - Rol Seç -</option>
  @foreach ($roles as $key => $item)
  <option value="{{ $item->id }}">{{ $item->role }}</option>
  @endforeach
  </select>
  </div>
  </div>



  </div>
  <div class="card-footer">
  <button class="btn btn-md btn-primary" type="submit"> Kaydet</button>
  <button class="btn btn-md btn-danger" type="reset"> Reset</button>
  </div>
  </form>
  </div>
  </div>
</div>

@endsection

resources/views/superuser/Settings/users/edit.blade.php
@extends('layouts.superuser-base')

@section('content')

<div class="row">
  <div class="col-12">
  <div class="card">
  <div class="card-header"><strong>Yeni Kullanıcı</strong> <small>Ekle</small> </div>
  <form action="" method="post" enctype="multipart/form-data">
    @csrf
  <div class="card-body">

  <div class="form-group row">
  <label class="col-md-2 col-form-label" for="text-input">Ad Soyad</label>
  <div class="col-md-10">
  <input class="form-control" id="text-input" type="text" name="ad-soyad" placeholder="Ad Soyad" value="{{ $user->name }}">
  </div>
  </div>
  <div class="form-group row">
  <label class="col-md-2 col-form-label" for="email-input">E-Mail</label>
  <div class="col-md-10">
  <input class="form-control" id="email-input" type="email" name="email" value="{{ $user->email }}" placeholder="ornek@gmail.com" autocomplete="email">
  </div>
  </div>
  <div class="form-group row">
  <label class="col-md-2 col-form-label" for="password-input">Şifre</label>
  <div class="col-md-10">
  <input class="form-control" aria-describedby="passHelp" id="password-input" type="password" name="password" placeholder="Şifre" autocomplete="new-password">
  <small id="passHelp" class="form-text text-muted">Herhangi Bir Şifre Girilmezse Eski Şifre Kullanılmaya Devam Edilecektir.</small>
  </div>
  </div>

  <div class="form-group row">
  <label class="col-md-2 col-form-label" for="select1">Rol</label>
  <div class="col-md-10">
  <select class="form-control" id="select1" name="role">
  <option value="null" selected disabled hidden> - Rol Seç -</option>
  @foreach ($roles as $key => $item)
  <option value="{{ $item->id }}" {{ $item->id === $user->role ? 'selected' : null }}>{{ $item->role }}</option>
  @endforeach
  </select>
  </div>
  </div>



  </div>
  <div class="card-footer">
  <button class="btn btn-md btn-primary" type="submit"> Kaydet</button>
  <button class="btn btn-md btn-danger" type="reset"> Reset</button>
  </div>
  </form>
  </div>
  </div>
</div>

@endsection

resources/views/superuser/Settings/users/index.blade.php
@extends('layouts.superuser-base')
@section('javascripts')
  <script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script>
@endsection
@section('head')
  <link href="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.css" rel="stylesheet">
@endsection

@section('yeni_ekle')
<a href="{{ route('superuser.Yeni Kullanıcı Ekle') }}" class="btn btn-success" type="button">Yeni Ekle</a>
@endsection

@section('content')

  <table
  id="table"
  data-toggle="table"
  data-pagination="true"
  data-side-pagination=""
  data-page-list="[10, 25, 50, 100, 200, All]" class="table table-responsive-sm table-striped">
  <thead>
    <tr>
      <th data-field="id">ID</th>
      <th data-field="name">Adı Soyadı</th>
      <th data-field="email">E-Posta</th>
      <th data-field="islemler">İşlemler</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($users as $key => $user)
      <tr>
      <td>{{ $user->id }}</td>
      <td>{{ $user->name }}</td>
      <td>{{ $user->email }}</td>
      <td>
        <a href="{{ route('superuser.Kullanıcı Düzenle',['id' => $user->id]) }}" class="btn btn-lg btn-primary" type="button">Düzenle</a>
        <a href="{{ route('superuser.settings_delete',['case' => 'userdel','userid' => $user->id]) }}" class="btn btn-lg btn-danger" type="button">Sil</a>
      </td>
      </tr>
    @endforeach

</tbody>

</table>

@endsection