routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Request as req;
use App\Models\UserRole;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register' => false]);

$restrictScope = function($roles){
    try {
        $result = UserRole::whereIn('role',$roles)->get()->pluck("id")->toArray();
        return implode(',',$result);
    } catch (\Throwable $th) {
        return null;
    }
};

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::middleware('checkRole:'.$restrictScope(['superuser']))->prefix('/superuser')->name('superuser.')->group(function () {
  // Superuser
  Route::get('/', 'Superuser\SuperuserController@index')->name('superuser');

  //Superuser - Settings
  Route::prefix('/settings')->group(function () {

    Route::match(['get','post'],'general', 'Superuser\SettingsController@general')->name('Genel Ayarlar');
    Route::get('newsletter', 'Superuser\SettingsController@newsletter')->name('Bülten İstekleri');

    // Settings - Users
    Route::prefix('users')->group(function(){
        Route::get('/', 'Superuser\SettingsController@users')->name('Kullanıcı Yönetimi');
        Route::match(['post','get'],'/create', 'Superuser\SettingsController@users_create')->name('Yeni Kullanıcı Ekle');
        Route::match(['post','get'],'/edit/{id}', 'Superuser\SettingsController@users_edit')->name('Kullanıcı Düzenle');
    });
    // Superuser - Settings - silme işlemleri
    Route::match(['get','post'],'del', 'Superuser\SettingsController@delete')->name('settings_delete');

  });

  //Superuser - Forms
  Route::prefix('/forms')->group(function () {
    Route::get('/', 'Superuser\FormController@index')->name('Formlar');
    Route::match(['get','post'],'edit/{id}', 'Superuser\FormController@FormEdit')->name('Form Düzenle');
    Route::match(['get','post'],'create', 'Superuser\FormController@FormCreate')->name('Form Oluştur');
  });

  //Superuser - CMS Yönetimi
  Route::prefix('/cms')->group(function () {
    Route::get('/{id}', 'Superuser\CmsController@index')->name('CMS Yönetimi');
    Route::match(['post','get'],'/create/{parent_id}', 'Superuser\CmsController@create')->name('İçerik Oluştur');
    Route::match(['post','get'],'/edit/{id}', 'Superuser\CmsController@edit')->name('İçerik Düzenle');
    Route::match(['post','get'],'/delete/{id}', 'Superuser\CmsController@delete')->name('İçerik Sil');
    Route::match(['post','get'],'/delete/file/{id}', 'Superuser\CmsController@fileDelete')->name('Dosya Sil');
  });


  //Superuser - Language
  Route::prefix('/language')->group(function () {
    Route::get('/', 'Superuser\LanguageController@index')->name('language');
    // Language - create,edit,delete
    Route::match(['get','post'],'create', 'Superuser\LanguageController@create')->name('language_create');
    Route::match(['get','post'],'edit/{id}', 'Superuser\LanguageController@edit')->name('language_edit');
    Route::get('delete/{id}', 'Superuser\LanguageController@delete')->name('language_delete');
    Route::get('initialize/{lang}', 'Superuser\LanguageController@initializeLanguage')->name('language_init');
    Route::get('checklangs', 'Superuser\LanguageController@checkLangs')->name('check languages');
  });

  //Superuser - System
  Route::prefix('/system')->group(function () {
    Route::get('/', 'Superuser\SystemController@index')->name('system');
    //cache clear
    Route::get('/clear/cache', 'Superuser\SystemController@cacheClear')->name('system.clearcache');

    //maintenance mode
    Route::get('/up', 'Superuser\SystemController@systemUp')->name('system.up');
    Route::get('/down', 'Superuser\SystemController@systemDown')->name('system.down');

    //migrate
    Route::get('/migrate', 'Admin\SystemController@databaseMigrate')->name('system.migrate');
  });

});

Route::middleware('checkRole:'.$restrictScope(['superuser','admin']))->prefix('/admin')->group(function () {
    // Admin
    Route::get('/', 'Admin\AdminController@index')->name('admin');

    //Admin - Settings
    Route::prefix('/settings')->group(function () {

      Route::match(['get','post'],'general', 'Admin\SettingsController@general')->name('Genel Ayarlar');
      Route::get('newsletter', 'Admin\SettingsController@newsletter')->name('Bülten İstekleri');

      // Settings - Users
      Route::prefix('users')->group(function(){
          Route::get('/', 'Admin\SettingsController@users')->name('Kullanıcı Yönetimi');
          Route::match(['post','get'],'/create', 'Admin\SettingsController@users_create')->name('Yeni Kullanıcı Ekle');
          Route::match(['post','get'],'/edit/{id}', 'Admin\SettingsController@users_edit')->name('Kullanıcı Düzenle');
      });
      // Admin - Settings - silme işlemleri
      Route::match(['get','post'],'del', 'Admin\SettingsController@delete')->name('settings_delete');

    });

    //Admin - Forms
    Route::prefix('/forms')->group(function () {
      Route::get('/', 'Admin\FormController@index')->name('Formlar');
      Route::match(['get','post'],'edit/{id}', 'Admin\FormController@FormEdit')->name('Form Düzenle');
      Route::match(['get','post'],'create', 'Admin\FormController@FormCreate')->name('Form Oluştur');
    });

    //Admin - CMS Yönetimi
    Route::prefix('/cms')->group(function () {
      Route::get('/{id}', 'Admin\CmsController@index')->name('CMS Yönetimi');
      Route::match(['post','get'],'/create/{parent_id}', 'Admin\CmsController@create')->name('İçerik Oluştur');
      Route::match(['post','get'],'/edit/{id}', 'Admin\CmsController@edit')->name('İçerik Düzenle');
      Route::match(['post','get'],'/delete/{id}', 'Admin\CmsController@delete')->name('İçerik Sil');
      Route::match(['post','get'],'/delete/file/{id}', 'Admin\CmsController@fileDelete')->name('Dosya Sil');
    });


    //Admin - Language
    Route::prefix('/language')->group(function () {
      Route::get('/', 'Admin\LanguageController@index')->name('language');
      // Language - create,edit,delete
      Route::match(['get','post'],'create', 'Admin\LanguageController@create')->name('language_create');
      Route::match(['get','post'],'edit/{id}', 'Admin\LanguageController@edit')->name('language_edit');
      Route::get('delete/{id}', 'Admin\LanguageController@delete')->name('language_delete');
      Route::get('initialize/{lang}', 'Admin\LanguageController@initializeLanguage')->name('language_init');
      Route::get('checklangs', 'Admin\LanguageController@checkLangs')->name('check languages');
    });

    //Admin - System
    Route::prefix('/system')->group(function () {
      Route::get('/', 'Admin\SystemController@index')->name('system');
        //cache clear
        Route::get('/clear/cache', 'Admin\SystemController@cacheClear')->name('system.clearcache');

        //maintenance mode
        Route::get('/up', 'Admin\SystemController@systemUp')->name('system.up');
        Route::get('/down', 'Admin\SystemController@systemDown')->name('system.down');

        //migrate
        Route::get('/migrate', 'Admin\SystemController@databaseMigrate')->name('system.migrate');
    });

  });

// Change Language slug Session
Route::post('/lang/changelang', function (Request $request) {
    $langQuery = DB::table('language')->where('slug',$request->input('change_lang'))->first();
    session(['lang_slug' => $request->input('change_lang'), 'lang_name' => $langQuery->name]);
    return redirect()->back();
})->name('ChangeLang');

// User
Route::middleware('checkRole:'.$restrictScope(['user']))->prefix('/user')->group(function () {
  // User
  Route::get('/', 'User\UserController@index')->name('user');

  //User - CMS Yönetimi
  Route::prefix('/cms')->group(function () {
    Route::get('/{id}', 'User\CmsController@index')->name('user.CMS Yönetimi');
    Route::match(['post','get'],'/create/{parent_id}', 'User\CmsController@create')->name('user.İçerik Oluştur');
    Route::match(['post','get'],'/edit/{id}', 'User\CmsController@edit')->name('user.İçerik Düzenle');
    Route::match(['post','get'],'/delete/{id}', 'User\CmsController@delete')->name('user.İçerik Sil');
    Route::match(['post','get'],'/delete/file/{id}', 'User\CmsController@fileDelete')->name('user.Dosya Sil');
  });

  // Settings - Profile Edit
  Route::match(['post','get'],'profile/edit/', 'User\SettingsController@users_edit')->name('Profil Düzenle');

});

//ajax ve json işlemleri
Route::prefix('/misc')->group(function (){
    Route::get('/json/{name}.json', 'Web\AjaxController@textToJson');
    Route::get('/download/{dosya}', 'Web\BaseController@getDownload')->name('download');
});

Route::get('/', 'Web\BaseController@index');
Route::get('/{slug}', 'Web\BaseController@index');
Route::get('/{language_id}/{slug}', 'Web\BaseController@index');

app/Http/Controllers/Admin/LanguageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use App\Models\CategoryLanguage;
use App\Models\Taxonomy;

class LanguageController extends Controller
{
    public function index(Request $request)
    {
      $data['languages'] = DB::table('language')->get();
      $lostContents = array();
      foreach ($data['languages'] as $key => $value) {
        $checkDB = DB::table("category_language")
        ->where('language_slug',$value->slug)
        ->doesntExist();
        if($checkDB){
            $lostContents[$key]['slug'] = $value->slug;
            $lostContents[$key]['name'] = $value->name;
        }
      }
      $data['lostContents'] = $lostContents;
      return view('admin.Language.index',$data);
    }

    public function checkLangs(Request $request)
    {
        //TODO: Listede olmayan fakat veritabanında olan dillerin kontrolü
      $languages = DB::table('language')
                            ->select("slug")
                            ->get()->map(function($value){
                                return $value->slug;
                            });

      return dd($languages);
    }

    public function create(Request $request)
    {
        if ($request->isMethod('post')) {
          $keys = $request->input('key');
          $dil_adi = $request->input('dil_adi');
          $dil_on_ek = $request->input('on_ek');
          if ($request->hasFile('bayrak')) {
              $bayrak = $request->bayrak->store('');
          }else {
            $bayrak = null;
          }
          $exist = DB::table('language')->where('slug', $dil_on_ek)->exists(); // eğer kayıt varsa 1 değerini döndürecek
          if ($exist != 1) {
              DB::table('language')->insert([
                'name' => $dil_adi,
                'slug' => $dil_on_ek,
                'image' => $bayrak
              ]);
              // Settings tablosuna bir satır ekliyor
              DB::table('settings')->insert([
                'language_id' => $dil_on_ek
              ]);

              //keyler ve degerler
              foreach ($keys as $key => $value) {
                $deger = $request->input("deger")[$key];

                    if (!empty($value)) {

                      DB::table('language_value')->insert([
                        'language_slug' => $dil_on_ek,
                        'language_key' => $value,
                        'language_value' => $deger
                      ]);

                    }
              }

              return redirect()->back()->with('success','Kayıt Başarıyla Eklendi');
          }else {
            return redirect()->back()->with('error','Bu Kayıt Zaten Var!');
          }


        }
        return view('admin.Language.create');
    }

    public function edit(Request $request,$id)
    {

      if ($request->isMethod('post')) {
        $keys = $request->input('key');
        $dil_adi = $request->input('dil_adi');
        $dil_on_ek = $request->input('on_ek');
        $bayrak_old = DB::table('language')->where("id",$id)->first();
        if ($request->hasFile('bayrak')) {
            Storage::delete($bayrak_old->image);
            $bayrak = $request->bayrak->store('');
        }else {
          $bayrak = $bayrak_old->image;
        }

            DB::table('language')->where('id',$id)->update([
              'name' => $dil_adi,
              'slug' => $dil_on_ek,
              'image' => $bayrak
            ]);

            //keyler ve degerler
            foreach ($keys as $key => $value) {
              $deger = $request->input("deger")[$key];

                  if (!empty($value)) {

                    DB::table('language_value')->updateOrInsert([
                      'id' => $key
                    ],[
                      'language_slug' => $dil_on_ek,
                      'language_key' => $value,
                      'language_value' => $deger
                    ]);

                  }else {
                    DB::table('language_value')->where('id',$key)->delete();
                  }
            }

            return redirect()->back()->with('success','Kayıt Başarıyla Eklendi');



      }

      $data['language'] = DB::table('language')->where("id",$id)->first();
      $data['language_keys'] = DB::table('language_value')->where("language_slug",$data['language']->slug)->get();
      return view('admin.Language.edit',$data);
    }

    public function delete(Request $request,$id)
    {

      if ($request->get('img')) {
        $bayrak_old = DB::table('language')->where("id",$id);
        Storage::delete($bayrak_old->first()->image);
        $bayrak_old->update([
          'image' => null
        ]);
        return redirect()->back()->with('success','Resim Başarıyla Silindi');
      }else {
        $onlyLang = $request->query('onlylang') ? true : false;
        $query = DB::table('language')->where("id",$id);
        Storage::delete($query->first()->image);
        DB::table('language_value')->where("language_slug",$query->first()->slug)->delete();
        if(!$onlyLang){
            // category_language tablosundaki bu dile ait verileri temizliyoruz
            $cl = DB::table("category_language")->where("language_slug",$query->first()->slug);
            // varsa resimleri de temizliyoruz
            foreach ($cl->get() as $key => $value) {
                if ($value->image) { Storage::delete($value->image); }
                if ($value->image2) { Storage::delete($value->image2); }
                if ($value->image3) { Storage::delete($value->image3); }
            }
            $cl->delete();
        }
        $query->delete();
        return redirect()->back()->with('success','Kayıt Başarıyla Silindi');
      }

    }

    public function initializeLanguage($language_slug){
        $c_count = DB::table('category')->count();
        $cl_count = DB::table('category_language')->where('language_slug',$language_slug)->count();
        if($cl_count == $c_count){
            return response()->json([
                "c_count" => $c_count,
                "cl_count" => $cl_count,
                "isNew" => false,
                "status" => true
            ]);
        }else{
            $category = DB::table('category')->get();
            $settings = DB::table('settings')->where('default_lang',1)->first();
            $default_language = $settings->language_id;
            foreach ($category as $key => $value) {

                //Category_language
                $recordDoesntExist = DB::table("category_language")
                                    ->where("category_id",$value->id)
                                    ->where("language_slug",$language_slug)
                                    ->doesntExist();
                if($recordDoesntExist){
                    $record = CategoryLanguage::where("category_id",$value->id)
                            ->where("language_slug",$default_language)
                            ->first();
                    $new_record = $record->replicate()->fill([
                        "language_slug" => $language_slug
                    ]);

                    // taxonomy
                    $tax = Taxonomy::where("category_id",$value->id)
                    ->where("language_slug",$default_language)
                    ->first();
                    $new_tax = $tax->replicate()->fill([
                        "language_slug" => $language_slug
                    ]);

                    //save
                    $new_record->save();
                    $new_tax->save();
                }
            }
            return response()->json([
                "isNew" => true,
                "status" => true
            ]);
        }
    }
}

resources/views/superuser/Language/create.blade.php
@extends('layouts.superuser-base')

@section('yeni_ekle')
<a href="{{ route('superuser.language_create') }}" class="btn btn-success" type="button">Yeni Ekle</a>
@endsection

@section('javascripts')
  <script type="text/javascript">
    $(function(){
      $("#add-new-key").click(function(){
        var copy = $('#KeyDegerBlock').clone();
        $(".card-body").append( copy );
        copy.find("input").val("");
      });
    });
  </script>
@endsection

@section('content')



  <div class="card">
  <form class="" method="post" enctype="multipart/form-data">
  @csrf
  <div class="card-header"><strong>Dil Yönetimi</strong></div>
  <div class="card-body">

  <div class="form-group">
  <label for="input1">Dil Adı</label>
  <input class="form-control" id="input1" name="dil_adi" type="text" placeholder="Dil Adı">
  </div>

  <div class="form-group">
  <label for="input2">Dil Ön Eki</label>
  <input class="form-control" id="input2" name="on_ek" type="text" placeholder="Dil Ön Eki">
  </div>

  <div class="custom-file col-6">
  <input type="file" class="custom-file-input" id="customFile" name="bayrak">
  <label class="custom-file-label" for="customFile">Bayrak</label>
  </div>

  <div class="clearfix"></div>
  <div class="row mt-5">
    <div class="col-4 text-left">
      <button class="btn btn-success" id="add-new-key" type="button">Yeni Key Ekle</button>
    </div>
  </div>

  <div class="row mt-2" id="KeyDegerBlock">
    <div class="form-group col-6">
    <label for="key1">Key</label>
    <input class="form-control" id="key1" name="key[]" type="text" placeholder="Key">
    </div>
    <div class="form-group col-6">
    <label for="deger1">Değer</label>
    <input class="form-control" id="deger1" name="deger[]" type="text" placeholder="Değer">
    </div>
  </div>

  </div>

  <div class="card-footer">
  <button class="btn btn-md btn-primary" type="submit"> Kaydet</button>
  <button class="btn btn-md btn-danger" type="reset"> Reset</button>
  </div>
</form>
  </div>



@endsection

resources/views/superuser/Language/edit.blade.php
@extends('layouts.superuser-base')

@section('yeni_ekle')
<a href="{{ route('superuser.language_create') }}" class="btn btn-success" type="button">Yeni Ekle</a>
@endsection

@section('javascripts')
  <script type="text/javascript">
    $(function(){
      $("#add-new-key").click(function(){
        var copy = $('#KeyDegerBlock').clone();
        $(".card-body").append( copy );
        copy.find("input").eq(0).attr('name','key[]').attr('value','');
        copy.find("input").eq(1).attr('name','deger[]').attr('value','');

      });
    });
  </script>
@endsection

@section('content')



  <div class="card">
  <form class="" method="post" enctype="multipart/form-data">
  @csrf
  <div class="card-header"><strong>Dil Yönetimi</strong></div>
  <div class="card-body">

  <div class="form-group">
  <label for="input1">Dil Adı</label>
  <input class="form-control" id="input1" name="dil_adi" type="text" placeholder="Dil Adı" value="{{ $language->name }}">
  </div>

  <div class="form-group">
  <label for="input2">Dil Ön Eki</label>
  <input class="form-control" id="input2" name="on_ek" type="text" placeholder="Dil Ön Eki" value="{{ $language->slug }}">
  </div>

  <div class="custom-file col-6">
  <input type="file" class="custom-file-input" id="customFile" name="bayrak">
  <label class="custom-file-label" for="customFile">Bayrak</label>
  </div>
  @if ($language->image)
    <div class="clearfix"></div>
    <div class="col-6 mt-2 pl-0">
         <img src="{{ asset("uploads/$language->image") }}" style="width:25%; height:auto;"><br>
         <span class="text-left">
           <a class="badge badge-danger" href="{{ route('superuser.language_delete',['id' => $language->id,'img' => true]) }}">Resmi Sil</a>
         </span>
    </div>
  @endif


  <div class="clearfix"></div>
  <div class="row mt-5">
    <div class="col-4 text-left">
      <button class="btn btn-success" id="add-new-key" type="button">Yeni Key Ekle</button>
    </div>
  </div>
  @foreach ($language_keys as $key => $value)

    <div class="row mt-2" @if ($key == 0) id="KeyDegerBlock" @endif>
      <div class="form-group col-6">
      <label for="key1">Key</label>
      <input class="form-control" id="key1" name="key[{{ $value->id }}]" type="text" placeholder="Key" value="{{ $value->language_key }}">
      </div>
      <div class="form-group col-6">
      <label for="deger1">Değer</label>
      <input class="form-control" id="deger1" name="deger[{{ $value->id }}]" type="text" placeholder="Değer" value="{{ $value->language_value }}">
      </div>
    </div>

  @endforeach


  </div>

  <div class="card-footer">
  <button class="btn btn-md btn-primary" type="submit"> Kaydet</button>
  <button class="btn btn-md btn-danger" type="reset"> Reset</button>
  </div>
</form>
  </div>



@endsection

resources/views/superuser/Language/index.blade.php
@extends('layouts.superuser-base')

@section('yeni_ekle')
<a href="{{ route('superuser.language_create') }}" class="btn btn-success" type="button">Yeni Ekle</a>
@endsection

@section('javascripts')
<script>
    $(function(){
        $(".init-lang").on('click',function(){
            var btn = $(this);
            var btnText = btn.text();
            btn.prop("disabled",true).html('<div class="spinner-border spinner-border-sm text-primary" role="status"></div>');
            let url = $(this).data("url");
            $.get(url).done(function(res){
                let popText = '';
                if(res.status === true && res.isNew === false){
                    popText = "Dil Zaten Senkronize Durumda !";
                }else if(res.status === true && res.isNew === true){
                    popText = 'Yeni Dil Başarıyla Senkronize Edildi!'
                }else{
                    popText = 'Something Went Wrong!';
                }
                btn.prop("disabled",false).html(btnText).css("background-color","#2eb85c").attr('data-content',popText).popover('show');
                setTimeout(() => {
                    btn.popover('hide');
                }, 2000);
            }).fail(function(err){
                console.error(err);
            });
            return false;
        })
        $("a#deleteLang").click(function(){
            let conf = confirm("Bu dili tüm içerikleriyle birlikte silmek ister misiniz?");
            if(conf){
                return true;
            }else{
                let url = $(this).attr("href") + "?onlylang=true";
                conf = confirm("Bu işlemi onayladığınızda; sadece dil silinecek fakat dile ait içerikler veritabanında kalmaya devam edecektir.");
                if(conf){
                    window.location = encodeURI(url);
                    return false;
                }else{
                    return false;
                }
            }
        });
    });
</script>
@endsection

@section('content')


  <table class="table mb-0 table-responsive-sm table-hover table-outline">
  <thead class="thead-light">
  <tr>
  <th>
  Adı <i class="fas fa-language"></i>
  </th>
  <th>Ön Eki</th>
  <th class="text-center">İşlemler</th>
  </tr>
  </thead>
  <tbody>

    @foreach ($languages as $key => $language)
      <tr>
        <td> {{ $language->name }} </td>
        <td> {{ $language->slug }} </td>
        <td class="text-right" width="35%">
        <button
        type="button"
        data-url="{{ route('superuser.language_init',([ 'lang' => $language->slug ])) }}"
        class="text-white btn btn-lg btn-warning init-lang"
        data-container="body"
        data-trigger="manual"
        data-toggle="popover"
        data-placement="top"
        style="min-width: 100px"
        data-content="Dil Başarıyla Senkronize Edildi">
            Senkronize et
        </button>
        <a href="{{ route('superuser.language_edit',([ 'id' => $language->id ])) }}" class="btn btn-lg btn-primary" type="button">Düzenle</a>
        <a href="{{ route('superuser.language_delete',([ 'id' => $language->id ])) }}" class="btn btn-lg btn-danger" id="deleteLang" type="button">Sil</a>
        </td>
      </tr>
    @endforeach



  </tbody>
  </table>

<small class="mt-3 w-100 d-block">
    @if($lostContents)
        Veritabanında,
        @foreach ($lostContents as $item)
            <strong>{{ $item["name"] }} {{ !$loop->last ? ',' : null }}</strong>
        @endforeach
        diline/dillerine Ait Verilerin kayıp olduğu görünüyor. lütfen dili senkronize ediniz.
        <br>
    @endif
</small>
@endsection